#!/usr/bin/env sh

while :
do
  git add -A .
  git commit -qm "git live commit"
  git push -q >> /dev/null
  git pull >> /dev/null
  if [[ $? -ne 0 ]];
  then
    git reset --hard HEAD >> /dev/null
  fi
  # comment
done

