#!/usr/bin/env sh
echo git live started
while :
do
  /usr/bin/git add -A .
  /usr/bin/git commit -m "$(/usr/bin/git diff --cached --name-only)" >> /dev/null
  /usr/bin/git push -q >> /dev/null
  /usr/bin/git pull >> /dev/null
  if [[ $? -ne 0 ]];
  then
    /usr/bin/git reset --hard origin/$(/usr/bin/git rev-parse --abbrev-ref HEAD) >> /dev/null
    /usr/bin/git clean -dff
    echo "Reset to origin"
  fi
done

