#!/usr/bin/env sh

while :
do
  git add -A .
  git commit -m "git live commit" >> /dev/null
  git push -q >> /dev/null
  git pull >> /dev/null
  if [[ $? -ne 0 ]];
  then
    git reset --hard HEAD >> /dev/null
  fi
done

